# Oppsett av automatisk bygg gjennom Azure pipelines
# Alle tags bygges og publiseres til Azure Container Registry
# - YAML-skjema https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema
# - Innebygde variable https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
# - Bruke variable https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch
# - Caching https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
# - Innebygde tasks https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops
# - Cache task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/cache?view=azure-devops
# - Maven task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops
# - Docker task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops
# - Bash task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops
# - Maven help:evaluate https://maven.apache.org/plugins/maven-help-plugin/evaluate-mojo.html

trigger:
  tags:
    include:
      - refs/tags/*

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  TAG: $(Build.SourceBranchName)

steps:
  - task: Bash@3
    displayName: 'Get maven project version'
    inputs:
      targetType: inline
      script: |
        'MAVEN_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)'
        'echo "##vso[task.setvariable variable=TAG]$MAVEN_PROJECT_VERSION"'
  - task: Cache@2
    displayName: Cache Maven local repo
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven
      path: $(MAVEN_CACHE_FOLDER)
  - task: Maven@3
    displayName: 'Maven package'
    inputs:
      goals: 'package'
      mavenOptions: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Dhttp.keepAlive=false -Dmaven.wagon.http.retryHandler.count=3'
      jdkVersionOption: 1.8
  - task: Docker@2
    displayName: 'Login to Azure Container Registry'
    inputs:
      command: 'login'
      containerRegistry: 'prodacrPremium1'
  - task: Docker@2
    displayName: 'Docker build and push'
    inputs:
      command: 'buildAndPush'
      repository: 'eformidling/efm-sr-proxy'
      tags: $(TAG)
