resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    includeDatetimeInTag: false
    dockerRepository: eformidling/efm-sr-proxy
    kubernetesManifestRepository: git://eformidling/eformidling
    kubernetesManifestFile: sr-proxy/sr-proxy.yaml

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - master
