resources:
  repositories:
    - repository: efm-eproc-pipeline
      type: github
      name: felleslosninger/efm-eproc-pipeline
      endpoint: felleslosninger
      ref: lock-docker-images

extends:
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters:
    environmentRepository: git://eformidling/eformidling

trigger:
  batch: true
  branches:
    include:
      - development
      - release-*
      - hotfix-*
      - master

pr: none
